### ISSUE TITLE
Bottom card issue

### ISSUE THREAD

**Issue by exus85** [DBuit/sidebar-card#45]
Hi, I have an issue with sidebar card:
when I refresh the page the bottom section of the sidebar doesn't appear and home assistant reports this error:
.../hacsfiles/sidebar-card/sidebar-card.js:462:2818 TypeError: a.setConfig is not a function

If I keep refreshing the page it shows up sometimes  (with no errors reported)  but most of the times it doesn't

browser console error reported:
Uncaught TypeError: a.setConfig is not a function
    firstUpdated http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:462
    setTimeout handler*firstUpdated http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:462
    performUpdate http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:134
    _enqueueUpdate http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:134
    requestUpdateInternal http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:134
    initialize http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:134
    initialize http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:159
    q http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:134
    K http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:159
    <anonymous> http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:412
    Ie http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:412
    Ie http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:412
    async* http://ipaddress:8123/hacsfiles/sidebar-card/sidebar-card.js:661
sidebar-card.js:462:2818

**Comment by kongjudas** [comment]
I have the same issue on my Lenovo Android using Chrome after upgrading to 2021.12 b1. It doesn't show at all. On my Mac, using Safari, it shows up randomly after some refreshes.

**Comment by Gilles-Clemenceau** [comment]
Same for me, it just appeared today.

**Comment by ivo-gofilex** [comment]
Same here, happens every time on HA 2021.12.1 / 0.1.8.3

**Comment by wtrbuit** [comment]
We are looking into the issue.

**Comment by ivohulsman** [comment]
Here is my bottomCard (I am ivo-gofilex, accidentally posted on the wrong account):

`bottomCard:
  type: vertical-stack
  cardOptions:
    cards:
      - type: custom:battery-state-card
        entities:
          - entity: sensor.op8pro_battery_level
            name: "OP8P"
          - entity: sensor.op6_battery_level
            name: "OP6"
          - entity: sensor.liv_tablet_battery_level
            name: "Tablet Office"
  cardStyle: |
    :host {
      width: 100%;
    }`

**Comment by wtrbuit** [comment]
What we have learned so far is that there is an issue with custom cards and with at least vertical-stack cards. Entities card does work. We will update you when we know more.

**Comment by Denow** [comment]
It seems to be related to a timing issue. If I open another page and then switch to the sidebar page, the bottom card is loaded. When I refresh on the sidebar page the bottom bar card does not load and gives the same error mentioned in this issue.

**Comment by Gilles-Clemenceau** [comment]
I have a lot of custom elements, but it was working since the last HA core update.

```
  bottomCard:
    type: vertical-stack
    cardOptions:
      cards:
        - type: custom:meteofrance-weather-card
          style: |
            ha-card {
              background: none;
              color: #fff;
              padding: 0px !important;
            }
          [...]
        - type: horizontal-stack
          style: |
            ha-card {
              background: none;
              color: #fff;              
            }
          cards:
            - type: entity
              entity: sensor.temperature_exterieure_temperature
              name: Exterieur
              style: |
                ha-card {
                  background: none;
                  padding: 0px!important;
                  margin: 0px!important;
                }
            - type: entity
              entity: sensor.temperature_salon_temperature
              name: Salon
              style: |
                ha-card {
                  background: none;
                  padding: 0px!important;
                  margin: 0px!important;
                }
            - type: entity
              entity: sensor.ipx800v4_piscine
              name: Piscine
              style: |
                ha-card {
                  background: none;
                  padding: 0px!important;
                  margin: 0px!important;
                }
        - type: custom:bar-card
          positions:
            icon: 'off'
          min: 0
          max: 5000
          animation:
            '0':
              state: 'on'
          entities:
            - entity: sensor.envoy_current_energy_consumption
              name: Consommation
            - entity: sensor.envoy_current_energy_production
              name: Production
          entity_row: true
    cardStyle: |
      :host {
        width: 100%;
        background: none;
      }
```

**Comment by nyffchanium** [comment]
> What we have learned so far is that there is an issue with custom cards and with at least vertical-stack cards. Entities card does work. We will update you when we know more.

For me, entities card doesn't work either:

```
sidebar:
  bottomCard:
    type: entities
    entities:
      - entity: sun.sun
```

```
hui-calendar-card.ts:31 Uncaught Error: Entities must be specified
    at HTMLElement.value (hui-calendar-card.ts:31)
    at sidebar-card.js?hacstag=2418255740184:462
```

![image](https://user-images.githubusercontent.com/55743116/147830231-a5dddeaa-3e73-41de-8fb8-25ad39a7b762.png)
![image](https://user-images.githubusercontent.com/55743116/147830279-6448e833-b00d-4a2c-b635-4f58662408d8.png)

Not sure whether the calendar card does have anything to do it.

**Comment by mvanlijden** [comment]
I also have the same error in my console with initially loading the sidebard bottom card.
Switching to another dashboard and back to the dashboard with the sidecard does work.
In my mind this error appeared when the 0.1.8.4 update, but this could also be the december HA update.

My config:
`  bottomCard:
    type: vertical-stack
    cardStyle: |
      :host {
        width: 100%;
      }
    cardOptions:
      cards:
        - type: weather-forecast
          entity: weather.openweathermap_hourly
          show_forecast: false
          name: ' '
          tap_action:
            action: navigate
            navigation_path: /lovelace-wallpanel/weer-detail
        - type: picture-entity
          camera_image: camera.buienradar
          entity: camera.buienradar
          show_state: false
          show_name: false
          camera_view: live`

**Comment by pafftis** [comment]
Good afternoon, I have the same problem the bottom panel does not work at all. I've tried all your versions. the problem does not go away. Apparently this is due to the latest Ha update
I really want you to fix it soon.
  bottomCard:
    type: vertical-stack
    cardOptions:
      cards:
        - type: custom:layout-card
          layout_type: custom:masonry-layout
          layout:
            width: 220
            max_cols: null
          cards:
            - type: custom:simple-weather-card
              entity: weather.cherepovets
              name: Череповец
              tap_action:
                action: navigate
                navigation_path: /dashboard-galaxy-tab/weather
          primary_info:
            - wind_bearing
            - humidity
          secondary_info:
            - precipitation
            - precipitation_probability
          backdrop:
            day: ' var (- primary-color) '
            night: ' # 40445a '

**Comment by fammastrodaiuto** [comment]
Good afternoon, I have the same problem the bottom panel does not work at all. 

Version side bar: 0.1.8.4
Version HA: core-2021.12.7
Version HA Supervisor: Home Assistant OS 7.1

Code:
  bottomCard:
    type: horizontal-stack
    cardOptions:
      cards:
        - type: entity-filter
          entities:
            - person.michael
          state_filter:
            - home
          card:
            type: custom:badge-card

Please fix it as soon as possible.
Thank you very much!

**Comment by Djhik** [comment]
Hello, I have this problem too, the display of the lower part of the sidebar is random.
I am available to do tests if necessary.

Error:

```
sidebar-card.js?hacstag=2418255740180:18071 
        
       Uncaught TypeError: cardElement.setConfig is not a function
    at :8123/hacsfiles/sidebar-card/sidebar-card.js?hacstag=2418255740180:18071:33
```

Info:

- Version HA: core-2021.12.10
- Version Supervisor: supervisor-2022.01.0
- Version Sidebar : 0.1.8.4

Code:

```
  bottomCard:
    type: vertical-stack
    cardOptions:
      cards:
        - type: 'horizontal-stack'
          cards:
            - type: custom:button-card
              entity: person.perso1
              triggers_update:
                ['person.julien', 'sensor.time']
              style:
                width: 15%
              tap_action: !include views/popup/perso1.yaml
              hold_action: !include views/popup/perso1.yaml
              template: temp_person2

            - type: custom:button-card
              entity: person.perso2
              triggers_update:
                ['person.lorie', 'sensor.time']
              style:
                width: 15%
              tap_action: !include views/popup/perso2.yaml
              hold_action: !include views/popup/perso2.yaml
              template: temp_person2

        - type: 'custom:mini-media-player'
          entity: media_player.volumio
          hide:
            name: true
            power: true
            source: true
            volume: true

        - type: 'custom:mini-graph-card'
          icon: 'mdi:home-thermometer-outline'
          entities:
            - sensor.sensor_chambre_perso3


```

**Comment by Gilles-Clemenceau** [comment]
Any news about this bug ?

**Comment by alinalihassan** [comment]
I can confirm it's still happening on my setup too. I had two dashboard and on one of them it works properly, the other one it doesn't with the same code, just different views. And if I first go to the functional dashboard, the other one works as well until I refresh.

**Comment by Desaydrone** [comment]
Hello everyone,

If  i write here, of course i got the same problem in the bottom part. But i realise something, when i put ine card in my dashboard with the same yaml code i put in the bottom part 

 A little exemple
![image](https://user-images.githubusercontent.com/15471688/153741571-f39b46c5-25ea-4598-ba0d-45d3c090c273.png)

**Comment by Alindil** [comment]
I have the same problem too

**Comment by neuroverflow** [comment]
It is indeed a "timer issue". Current value is 2ms, I changed it to 5000ms and it loads properly

**Comment by Gilles-Clemenceau** [comment]
> It is indeed a "timer issue". Current value is 2ms, I changed it to 5000ms and it loads properly

Where to change this value?

**Comment by flixlix** [comment]
> > It is indeed a "timer issue". Current value is 2ms, I changed it to 5000ms and it loads properly
> 
> Where to change this value?

I couldn't find this value either

**Comment by neuroverflow** [comment]
Line 462 
But let's be clear, this is a really ugly patch. Don't forget to delete the .js.gz file and only keep your modified sidebar-card.js as HASS always prefer to read that file first. 

![image](https://user-images.githubusercontent.com/65546298/153850596-b70da845-ff77-4ac1-8819-1c164bb4b447.png)

**Comment by pqpxo** [comment]
> 

Hey there!

I attempted to amend the file with the same '5000' value but my HA went into Safe Mode.

Any certain way of making this change?

**Comment by Gilles-Clemenceau** [comment]
I've made the change but it's not working for me. :-/

**Comment by neuroverflow** [comment]
Make sure you delete the .gz file if you changed the. Js. Otherwise Hass read the Js inside the archive.

**Comment by neuroverflow** [comment]
> > 
> 
> Hey there!
> 
> I attempted to amend the file with the same '5000' value but my HA went into Safe Mode.
> 
> Any certain way of making this change?

You probably remove a character like the comma. Make sure your editor supports the encoding, avoid notepad ;)

**Comment by pqpxo** [comment]
> > > 
> > 
> > 
> > Hey there!
> > I attempted to amend the file with the same '5000' value but my HA went into Safe Mode.
> > Any certain way of making this change?
> 
> You probably remove a character like the comma. Make sure your editor supports the encoding, avoid notepad ;)

False alarm! It looks like I changed something else and hadn't restarted in quite some time. 

Made the correction and now the bottom card works!

**Comment by Gilles-Clemenceau** [comment]
> Make sure you delete the .gz file if you changed the. Js. Otherwise Hass read the Js inside the archive.

Yes & I've checked in lovelace, I can see the modification. Maybe I have another bug.

**Comment by atika1988** [comment]
> Mindenképpen törölje a .gz fájlt, ha módosította a. Js. Ellenkező esetben Hass elolvasta a J-ket az archívumban.

a .gz where can i find the file?

**Comment by jchhenderson** [comment]
I think I have a similar issue.  My error in the log is:
> Logger: frontend.js.latest.202202031
> Source: components/system_log/__init__.py:190 
> First occurred: 13:14:48 (1 occurrences) 
> Last logged: 13:14:48
> 
> http://dietpi:8123/hacsfiles/sidebar-card/sidebar-card.js:462:18967 TypeError: a.setConfig is not a function. (In 'a.setConfig(e)', 'a.setConfig' is undefined)

It's a custom:button that only shows after a refreshing the screen.

Happy to make this a different issue if necessary.

**Comment by neuroverflow** [comment]
> > Mindenképpen törölje a .gz fájlt, ha módosította a. Js. Ellenkező esetben Hass elolvasta a J-ket az archívumban.
> 
> a .gz where can i find the file? I FOUND IT! :)
> 
> .gz has been deleted but still does not appear :(
> 
> what the problem?

Can be cache, make sure to clean the cache of your client.

**Comment by MattHoy** [comment]
Changing to 5000 and deleting the .gz did not resolve for me, tried bouncing HA and clearing my cache.

**Comment by mvanlijden** [comment]
@DBuit any update or idea on this?

**Comment by Gilles-Clemenceau** [comment]
> Changing to 5000 and deleting the .gz did not resolve for me, tried bouncing HA and clearing my cache.

For me, it's working sometimes. It depends on the page where I clear the cache. :-/

**Comment by mn-box** [comment]
Any update or idea on a solution? Keen to use the bottom card!

**Comment by ryanm7780** [comment]
> Any update or idea on a solution? Keen to use the bottom card!

Same here.  I love the idea of this, but not being able to use custom cards makes it way less useful.

**Comment by neuroverflow** [comment]
the patch I mentioned above works. I use it everyday and a few confirmed it's correct

**Comment by mn-box** [comment]
Mmm, the patch works but not always. It seems to work if I access the home navigation page only, but if I reload any of the other navigation pages it doesn't appear. This workaround is of course better than nothing... as I can make sure to always enter via home. But I can still end-up without bottom card if I click too quickly on one of the other navigation links after the page loads...

Hope this helps to find the solution....

**Comment by MetroAffe** [comment]
I like this sidebar card soo much but not without the bottom cards :(
Please fix that! Its a long time ago since the bug was opened

**Comment by Ming-A** [comment]
same issue here

**Comment by mn-box** [comment]
As a workaround, create a small custom card that for the botton card (e.g. WiFi QR button) and use that same card on your home page at the bottom. Only one of the botton cards needs to be repeated for this to work.

**Comment by MetroAffe** [comment]
neither the patch nor the workaround works for me on IOS (App, Safari, Chrome - Desktop mode)

**Comment by nyffchanium** [comment]
It looks like there are two distinct problems:
1. Home Assistant does not register all available cards as custom elements.
From my observations:
registered on initial load: all custom cards, core cards used by the initial view when loading the page.
registered when navigating to another view: cards used by the new view
Navigating does not remove registrations, it only adds missing card types.
You can see this by looking at `window.customElements`.
2. Timing. Even when all card types required for the bottom card are registered through the initial view, this takes some time, and the original 2ms might not be enough.

This also explains why neither the patch nor the workaround work for everyone.

So what currently works for me:
- Change the timeout (as mentioned [here](https://github.com/DBuit/sidebar-card/issues/45#issuecomment-1038940029)) to something that works for you, this will depend on the browser & device.
- Make sure you have all the card types you want to use in the bottom card in your initial view.
This will probably still not work if you change views too quickly on load. For this case, I guess, you would have to add all types to all views.

As for how this could be fixed:
One way to at least avoid the ugly timer hack, would be to use [CustomElementRegistry.whenDefined()](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined) to wait for the card type(s) to be defined.
For this to work properly with cards that have sub-cards, one would have to recursively search the config object for other card types. I guess that could work pretty ok-ish if you look for things like:
```yml
card:
  type: card-type
# or
cards:
  - type: card-type
```

How to get Home Assistant to register the custom elements in the first place, I have no idea.

**Comment by 400HPMustang** [comment]
> Line 462 But let's be clear, this is a really ugly patch. Don't forget to delete the .js.gz file and only keep your modified sidebar-card.js as HASS always prefer to read that file first.
> 
> ![image](https://user-images.githubusercontent.com/65546298/153850596-b70da845-ff77-4ac1-8819-1c164bb4b447.png)

Where do I find the file that is referenced here?

**Comment by Krispkiwi** [comment]
Any work on this?

**Comment by seanharsh** [comment]
Just another workaround that seems to load the bottom cards fairly consistently now.

In addition to increasing the error timeout to 5000, you can also use the preload card: https://github.com/gadgetchnnel/lovelace-card-preloader to load all cards that you are including in the bottom of the sidebar.

For example, the in top of my lovelace yaml, I am calling the preloader for these cards types I am using in my sidebar:

preload:
  - conditional
  - entities
  - glance
  - horizontal-stack
  - vertical-stack
  - custom:simple-weather-card
  - picture-entity
  - custom:mini-graph-card

There is still a little bit of a delay, but the cards do seem to load most times for me using this.

**Comment by 400HPMustang** [comment]
> Just another workaround that seems to load the bottom cards fairly consistently now.
> 
> In addition to increasing the error timeout to 5000, you can also use the preload card: https://github.com/gadgetchnnel/lovelace-card-preloader to load all cards that you are including in the bottom of the sidebar.
> 
> For example, the in top of my lovelace yaml, I am calling the preloader for these cards types I am using in my sidebar:
> 
> preload:
> 
> * conditional
> * entities
> * glance
> * horizontal-stack
> * vertical-stack
> * custom:simple-weather-card
> * picture-entity
> * custom:mini-graph-card
> 
> There is still a little bit of a delay, but the cards do seem to load most times for me using this.

Well that takes consistently 5 seconds to load the cards when I set it up but I still have problems where the sidebar doesn't load at all in some cases on some dashboards.

**Comment by karimbizid** [comment]
I have the card showing up while restarting the browser again.
As soon as I refresh the page the card is gone until I close the browser and reopen it again.
Workaround of adding the same card to my layout doesn't work for me.

**Comment by daytonturner** [comment]
Has anyone made any progress getting this to work in something like Fully Kiosk Browser?  I can get it to load pretty reliably using the preload and 5sec buffer tricks above, but still have absolutely no luck when loading inside of fully kiosk browser.

**Comment by nghetienhiep** [comment]
My steps.
Go to release and download the latest version.
In the file sidebar-card.js find "Bottom card config error!", look to the right there is a string ",2)" replace it with a number greater than 2000.
It works for me.

**Comment by sparment** [comment]
@nghetienhiep I'm having the issue noted here and do not see the ",2)" string in your recommended change above. It's been a while since your post... any suggestions?

**Comment by sparment** [comment]
I found the string to correct and updated the value to "5000)" from "2)"; but I'm still having the same problem.
Perhaps the suggested change only worked for prior versions of sidebar card? Has anyone tried this fix with version 0.1.9.2?

**Comment by sparment** [comment]
@neuroverflow any chance you are using the most recent version of sidebar-card and have it working? I can't get this to work and the code in your post above looks different than the current code.

**Comment by mn-box** [comment]
Same here. My previous approach to repeat 1-2 bottom card in the main screen doesn't work anymore and I am unable to get the bottom card to work. THanks!

**Comment by epj3** [comment]
Same here. Latest version of everything, doesn't reliably load bottom cards.

**Comment by Xionax** [comment]
Same here

**Comment by ronaldvdmeer** [comment]
I had the same problem but I think I can reproduce and "solve" it with a workaround. When the main section of my dashboard does not start or have a `vertical-stack` in it the bottom card on the sidebar does not work. To be more specific;

**Works**
```views:
  - title: home
    path: home
    type: custom:grid-layout
    layout:
      max_cols: 3
      grid-template-columns: 50px auto 50px
      grid-template-row: auto
      grid-template-areas: |
        ". main ."
    theme: custom-tablet
    subview: true
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entity
            entity: sensor.time
        view_layout:
          grid-area: main
```

**Does not work.** 
```views:
  - title: home
    path: home
    type: custom:grid-layout
    layout:
      max_cols: 3
      grid-template-columns: 50px auto 50px
      grid-template-row: auto
      grid-template-areas: |
        ". main ."
    theme: custom-tablet
    subview: true
    badges: []
    cards:
      - type: entity
        entity: sensor.time
        view_layout:
          grid-area: main
```

This is what I see in the console of my browser:
<img width="672" alt="image" src="https://github.com/DBuit/sidebar-card/assets/19911658/db1f0658-c0be-42e5-a7ca-36aeb5d838bd">

@DBuit Hope this helps

Related: https://github.com/DBuit/sidebar-card/issues/90

**Comment by mn-box** [comment]
Thanks Ronald, I can confirm this workaround is working for me.

**Comment by Xionax** [comment]
Works for me as well

**Comment by blaiser72** [comment]
I tried the vertical-stack solution but without success, then I inserted a custom:vertical-stack and the problem disappeared, 5 out of 5 refreshes both in chrome and android, working for me.

Thanks for the tips everyone!

ES:
**Sidebar bottom section:**

  bottomCard:
    type: custom:vertical-stack-in-card
    cardOptions:
      cards:
        - type: horizontal-stack
          cards:
            - type: custom:mushroom-person-card
---------------------------------------------------------

**Comment by Xionax** [comment]
My hypothesis is that in the bottomCard area a `type` is used but is not set with the correct parameters. When you use the same `type` in the mainarea of the dashboard the parameter is added and all works fine. Perhaps its a long shot but this is what my gut is telling me.

**Comment by mn-box** [comment]
I don't know about you, but for me the problem has gotten worst (even when using the workaround from above). I love this sidebar so much but without this bottom card....

Anybody got a solution (either using sidebar or using a different HACS integration)?

**Comment by GertVanderstukken** [comment]
Same here...
The bottom Card is not working reliable on a PC (Google Chrome) and it is not showing at all on a tablet (using Fully Kiosk Browser).
Anybody any ideas?

**Comment by DBuit** [comment]
The problem with the bottemCard is that somehow sometimes the card you wanna load is not yet available or not known as customElement so it cannot set the config it is trying to. I tried alot also some preload plugin for card but it does not make it work. Still searching but now alot of ideas.

**Comment by rVlad93** [comment]
This is still an issue. Is it fixed and we're doing something wrong?

**Comment by Crazycoder445** [comment]
I have the same problem probably 1/20 refreshes it works.

**Comment by adamtiley** [comment]
Still have the same issue, did we ever find a solid fix?

**Comment by Tman-Tech** [comment]
> Still have the same issue, did we ever find a solid fix?

https://github.com/DBuit/sidebar-card/issues/90#issuecomment-2176950746

I had a fix in this post.

**Comment by rVlad93** [comment]
It seems that it has a problem with the horizontal stack card. I tried it with a different card and it loads just fine.
